basePath: /api/v1
definitions:
  models.ErrorTraitResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.Plant:
    properties:
      name:
        type: string
      traits:
        items:
          $ref: '#/definitions/models.Trait'
        type: array
    type: object
  models.Trait:
    properties:
      dominant:
        type: boolean
      geneLabel:
        type: string
      name:
        type: string
    type: object
  models.TraitCombination:
    properties:
      description:
        type: string
      genotype:
        type: string
      numberOfPlants:
        type: integer
      percentage:
        type: number
    type: object
  models.TraitRequest:
    properties:
      fatherPlant:
        $ref: '#/definitions/models.Plant'
      motherPlant:
        $ref: '#/definitions/models.Plant'
      plantCount:
        type: integer
    type: object
  models.TraitResponse:
    properties:
      combinations:
        items:
          $ref: '#/definitions/models.TraitCombination'
        type: array
      fatherPlantName:
        type: string
      motherPlantName:
        type: string
      plantCount:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: A Go REST API that calculates F2 generation probabilities in plant
    breeding genetics. Calculate inheritance patterns and expected phenotype distributions
    based on parent plant genotypes. Features Swagger documentation and handles multiple
    genetic traits with dominant/recessive expressions.
  title: Pepper Analytics API
  version: "1.0"
paths:
  /trait-probability:
    post:
      consumes:
      - application/json
      description: Calculate the probability of a trait based on the genotype of two
        plants
      parameters:
      - description: Trait probability calculation request
        in: body
        name: trait
        required: true
        schema:
          $ref: '#/definitions/models.TraitRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TraitResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorTraitResponse'
      summary: Calculate Trait Probability
      tags:
      - trait-probability
schemes:
- http
- https
swagger: "2.0"
